# Open Graph protocol | OG åè®®
open_graph: true

# User info | ç”¨æˆ·ä¿¡æ¯
user:
  name: æ— é—»æ²™æ´²
  first_name: æ²™æ´²
  last_name: æ— é—»
  email: shinotak@foxmail.com
  domain: https://wangzai-zzy.github.io
  avatar: /images/avatar.png
  describe: è®©æƒ…ç»ªè¢«çœ‹è§ï¼Œè®©ç—›è‹¦è¢«è¨€è¯´ã€‚

# Individually configured friend link information | å‹é“¾è¯´æ˜é…ç½®
links_info:
  name: æ— é—»æ²™æ´²
  url: https://wangzai-zzy.github.io
  avatar: /images/avatar.png
  describe: è®©æƒ…ç»ªè¢«çœ‹è§ï¼Œè®©ç—›è‹¦è¢«è¨€è¯´ã€‚
  rule_text: æš‚ä¸æ¥å—ä¸ªäººåšå®¢ä»¥å¤–çš„å‹é“¾ç”³è¯·ï¼Œç¡®ä¿æ‚¨çš„ç½‘ç«™å†…å®¹ç§¯æå‘ä¸Šï¼Œæ–‡ç« è‡³å°‘5ç¯‡ï¼ŒåŸåˆ›70%ä»¥ä¸Šï¼Œéƒ¨ç½²HTTPSã€‚

# Site logo | ç½‘ç«™å›¾æ ‡
favicon:
  logo: /images/favicon.png
  dark_logo: /images/favicon_dark.png
  icon16: /images/favicon.png
  icon32: /images/favicon.png
  apple_touch_icon: /images/favicon.png
  visibilitychange: false # Enable toggle title display when leaving | å¼€å¯ç¦»å¼€æ—¶åˆ‡æ¢æ ‡é¢˜æ˜¾ç¤º
  hidden: /failure.ico
  show_text: favicon.show_text
  hide_text: favicon.hide_text

# Theme resource files or plug-ins | æ’ä»¶é…ç½®
assets:
  internal_provider: local # The cdn configuration of the js inside the theme | ä¸»é¢˜è„šæœ¬çš„ CDN é…ç½®
  third_party_provider: unpkg # cdn configuration of third-party js | ç¬¬ä¸‰æ–¹æ’ä»¶ CDN é…ç½®
  plugin: # The plug-in used by the theme
    hexo_theme_async:
      rowcss: css/plugins/bootstrap.row.css
      typing: js/plugins/typing.js
      search: js/plugins/local_search.js
      danmu: js/plugins/danmu.js
      main: js/main.js
  icons: # Icon configuration
    type: font # font symbol
    css:  //at.alicdn.com/t/c/font_3549054_n096xdrq7me.css
    js: # icon js

# CDN User - defined plug-in
cdn:
  css: 
  js:
    head:
    base: 
    async: 
    defer: 

# The icon used by the theme | ä¸»é¢˜å›¾æ ‡
icons:
  sun: iconfont icon-sun # Theme switch icon | ä¸»é¢˜åˆ‡æ¢æ˜äº®å›¾æ ‡
  moon: iconfont icon-moon # Theme switch icon | ä¸»é¢˜åˆ‡æ¢æš—é»‘å›¾æ ‡
  play: iconfont icon-play-circle # Home video play | é¦–é¡µæ’­æ”¾æŒ‰é’®å›¾æ ‡
  email: iconfont icon-envelope # email icon | é‚®ä»¶å›¾æ ‡
  next: iconfont icon-arrow-alt-circle-rig # Category entry icon | åˆ†ç±»å¡ç‰‡å…¥å£å›¾æ ‡
  calendar: iconfont icon-calendar-alt # Date of article details | æ–‡ç« è¯¦æƒ…æ—¥æœŸå›¾æ ‡
  clock: iconfont icon-clock # Article details time | æ–‡ç« è¯¦æƒ…æ—¶é—´å›¾æ ‡
  user: iconfont icon-user1 # Author of article details | æ–‡ç« è¯¦æƒ…ä½œè€…å›¾æ ‡
  back_top: iconfont icon-arrow-alt-circle-up # Return to the top icon | è¿”å›é¡¶éƒ¨å›¾æ ‡
  close: iconfont icon-times-circle # close icon | å…³é—­å›¾æ ‡
  search: iconfont icon-search # search icon | æŸ¥è¯¢å›¾æ ‡
  reward: iconfont icon-hand-holding-usd # reward icon | æ‰“èµå›¾æ ‡
  user_tag: iconfont icon-user 
  toc_tag: iconfont icon-th-list # toc icon | ç›®å½•å›¾æ ‡
  read: iconfont icon-book-reader # Secure the button in the lower right corner | é˜…è¯»æ¨¡å¼å›¾æ ‡
  arrows: iconfont icon-arrows-alt-h # Single bar and double bar toggle icon | å•æ å’ŒåŒæ åˆ‡æ¢å›¾æ ‡
  double_arrows: iconfont icon-angle-double-down # Code highlight fold icon | ä»£ç å—æŠ˜å å›¾æ ‡
  copy: iconfont icon-copy # Code copy icon | ä»£ç å—å¤åˆ¶å›¾æ ‡

# Top navigation menu | å¯¼èˆªæ   
top_bars:
  - title: ä¸»é¡µ
    url: /
  - title: å½’æ¡£
    url: /archives/
  - title: é“¾æ¥
    url: /links/
  - title: å…³äº
    url: /about/

# Banner settings | æ¨ªå¹…é…ç½®
banner:
  use_cover: false
  danmu: 
    enable: false
    el: .trm-banner
  default:
    type: img
    bgurl: https://s2.loli.net/2024/07/29/bUwSQrg95tfeiHN.jpg
    position: top
    fit: cover
  index:
    type: img
    bgurl: https://s2.loli.net/2024/07/29/1G96t2w7XDENdf4.jpg
    banner_title: æˆ‘çŸ¥é“ï¼Œ<br>æ˜¯æµæ˜Ÿèµç¾äº†é»‘å¤œï¼Œ<br>é²¸é±¼å®‰æ…°äº†å¤§æµ·ã€‚
  archive:
    type: img
    bgurl: https://s2.loli.net/2024/07/29/4G2KZkqmz8QlHY9.jpg
    banner_title: æ¼«æ¸¸è€…å‘æ¸…æ™¨ç»¿è‰²çš„åœ°å¸¦é™è½ï¼Œ<br>ä¸‡ç‰©ç‡ƒçƒ§ã€‚
  links:
    type: img
    bgurl: https://s2.loli.net/2025/06/08/pks4F3qCoMfDQrl.jpg
    banner_title: å¹¶éå› ä¸ºä¿¡ä»»æ‰å»äº†è§£ï¼Œ<br>è€Œæ˜¯å› ä¸ºæƒ³è¦ä¿¡ä»»ã€æƒ³è¦äº†è§£ã€‚
  about:
    type: img
    bgurl: https://s2.loli.net/2025/03/29/BmnrKGcloT3NSwa.jpg
    banner_title: FACE THE SIN, <br>SAVE THE E.G.O.

# Sidebar settings | ä¾§æ 
sidebar:
  typed_text_prefix: 
  typed_text: [ 'ä¸–äº‹è¯¡è°²ï¼Œè°¨è‡´è‰¯çŸ¥', 'ä½†è¡Œå¥½äº‹ï¼Œè«é—®å‰ç¨‹' ]
  info: 
    - key: Residence
      val: Earth
  social:
    - name: BiliBili
      icon: iconfont icon-bilibili-fill
      url: https://space.bilibili.com/449552577
    - name: Weibo
      icon: iconfont icon-weibo-fill
      url: https://weibo.com/u/7348512128/
    - name: Steam
      icon: iconfont icon-steam1
      url: https://steamcommunity.com/profiles/76561198976175627/
    - name: Github
      icon: iconfont icon-github
      url: https://github.com/WangZai-ZZY

# About page settings | å…³äºé¡µ
about:
  insert: none # before | after | none
  title: åœ¨è¿·èŒ«çš„æ—¶å€™ï¼Œäººåº”è¯¥é¡ºç€è‡ªå·±ä¸ç°å®çš„è”ç³»â€”â€”æ— è®ºé‚£æ˜¯ä¸€ç§ç”Ÿæ´»ï¼Œè¿˜æ˜¯ä¸€ç§ç†æƒ³â€”â€”å»å¯»æ‰¾æ–¹å‘ã€‚
  introduction: 
    å—¨ï¼è¿™é‡Œæ˜¯<strong>æ±ªå´½zzy</strong>ï¼Œæ¬¢è¿å…‰ä¸´æˆ‘çš„åšå®¢ğŸ‰ï¼<br>
    <br>
    æˆ‘å§‹ç»ˆè®¤ä¸ºï¼Œæ ‡ç­¾åªèƒ½é™ä½äº¤å¾€çš„æˆæœ¬ï¼Œæ— æ³•çœŸæ­£è§¦åŠä¸€ä¸ªäººçš„å†…åœ¨ã€‚<br>
    äººä¸äººä¹‹é—´çš„ç†è§£ä¸å…³æ€€ï¼Œæ˜¯ä»æ‰¿è®¤å¯¹æ–¹è¡Œä¸ºå…·æœ‰æ­£å½“æ€§ã€è§¦ç¢°å¹¶æ¥æ´½å¯¹æ–¹çš„æƒ…ç»ªå¼€å§‹çš„ã€‚<br>
    <br>
    æ‰€ä»¥ï¼Œæˆ‘å¼€è®¾äº†è‡ªå·±çš„åšå®¢ï¼Œå¸Œæœ›é€šè¿‡æ–‡å­—è¿™ä¸€è½½ä½“ï¼Œå¯„å®¿æˆ‘çš„æƒ…æ„Ÿï¼Œå‘è®¿é—®è€…ä¼ è¾¾ã€‚<br>
    æ— è®ºä½ æ˜¯å¦å¯¹æˆ‘è®²è¿°çš„æ•…äº‹äº§ç”Ÿäº†å…´è¶£ï¼Œæˆ‘éƒ½ååˆ†æ„Ÿè°¢ä½ çš„åˆ°è®¿â€”â€”<br>
    å› ä¸ºä½ çš„åˆ°æ¥ï¼Œæ‰è®©è¿™å¤„é™æ»ä¹‹åœ°æœ‰äº†æ„ä¹‰ã€‚
  blog: 
    <ul class="trm-list">
      <li>ä¸»é¡µé¡¶æ å›¾ï¼š<a href="http://www.uchor.com/U/1024975">ã€Œå››æ—¥ç«å…‰èŠ‚ã€-by. ç‹›çº³ä¸–ç•Œ</a></li>
      <li>å½’æ¡£é¡¶æ å›¾ï¼š<a href="https://hanyijie.lofter.com/post/d7b61_1cc897861">ã€Œè‰¾é›…æ³•æ‹‰ã€-by. éŸ©ä¸€æ°</a></li>
      <li>é“¾æ¥é¡¶æ å›¾ï¼š<a href="https://www.bilibili.com/opus/991046261720219664">ã€Œæ˜æ—¥æ–¹èˆŸ 2024æ„Ÿè°¢åº†å…¸ç‰¹åˆ«ç›´æ’­å®£ä¼ å›¾ã€</a></li>
      <li>é“¾æ¥é¡¶æ å›¾ï¼š<a href="https://x.com/paofannu/status/1900508030904758372">ã€Œé˜¿ç±³å¨…ã€by. paofannu</a></li>
    </ul>

# Footer settings | é¡µè„š
footer:
  # Hexo link (Powered by Hexo).
  powered: # ç¨‹åºé©±åŠ¨ä¿¡æ¯
    enable: true
  # Beian icp information for Chinese users. In China, every legal website should have a beian icp in website footer.
  # https://beian.miit.gov.cn/
  beian: # å¤‡æ¡ˆä¿¡æ¯
    enable: false
    icp: 
  # Copyright date ç‰ˆæƒæ—¥æœŸ
  copyright_year: 2021
  # è¿è¡Œæ—¶é—´
  live_time:
    enable: false
    prefix: footer.tips
    start_time: 04/10/2022 17:00:00
  # è‡ªå®šä¹‰å†…å®¹
  custom_text: Hosted by <a href="https://github.com" rel="noopener" target="_blank">&nbsp;Github Pages</a>

# Here is a collection of articles related to configuration.
#### Article configuration start ###

# Reward (Donate) | æ‰“èµ
# If enable true, reward would be displayed in every posts and pages by default.
# You can show or hide reward in a specific page throuth `reward: true | false` in Front Matter.
reward:
  enable: false
  comment: reward.comment
  # url:
  methods:

# Article table of contents | æ–‡ç« ç›®å½•
toc:
  enable: true
  list_number: true
  post_title: true
  max_depth: 3
  min_depth: 1

# Archive page | å½’æ¡£é¡µ
archive:
  type: more # less more

# Creative Commons 4.0 International License.
# https://creativecommons.org/licenses/
# Available values of license: by | by-nc | by-nc-nd | by-nc-sa | by-nd | by-sa | zero
# You can set a language value if you prefer a translated version of CC license.
# CC licenses are available in 39 languages, where you can find the specific and correct abbreviation you need.
# Valid values of language: deed.zh, deed.en, deed.ja, etc.
creative_commons:
  license: by-nc-sa
  language: deed.zh
  post: false
  clipboard: false

# Customize the cover image | å°é¢å›¾
cover:
  default: /images/block_default.jpg
  type: date # img || date || random

# The previous and the next article | ä¸Šä¸‹ç¯‡æ–‡ç« 
post_pagination: 
  enable: true 
  type: small # large || small

# img loading="lazy" | å›¾ç‰‡æ‡’åŠ è½½
lazyload:
  enable: true

# Displays outdated notice for a post | æ–‡ç« è¿‡æœŸæé†’
notice_outdate:
  enable: false
  style: flat # style: simple/flat
  limit_day: 365 # When will it be shown
  position: top # position: top/bottom
#### Article configuration end ###

# Page Visit Statistics
web_analytics:  
  enable: false 
  baidu:   # Baidu key
  google:  # Tracking ID for Google statistics
  tencent: # Tencent statistics
    sid:
    cid:

# comment
comment:
  bComments:
    enable: false
    env: # è…¾è®¯äº‘ç¯å¢ƒid
  twikoo:
    enable: false
    envId:   # è…¾è®¯äº‘ç¯å¢ƒid
  # region: # ç¯å¢ƒåœ°åŸŸï¼Œé»˜è®¤ä¸º ap-shanghaiï¼Œå¦‚æœæ‚¨çš„ç¯å¢ƒåœ°åŸŸä¸æ˜¯ä¸Šæµ·ï¼Œéœ€ä¼ æ­¤å‚æ•°
  # option: # ç”¨äºåŒºåˆ†ä¸åŒæ–‡ç« çš„è‡ªå®šä¹‰ js è·¯å¾„ï¼Œå¦‚æœæ‚¨çš„æ–‡ç« è·¯å¾„ä¸æ˜¯ location.pathnameï¼Œéœ€ä¼ æ­¤å‚æ•°
  giscus:
    enable: false
    repo:
    repo-id:
    category:
    category-id:
    mapping: pathname
    reactions-enabled: 1
    emit-metadata: 0
    lang: zh-CN
    theme: 
      light: light
      dark: transparent_dark

# Theme mode | ä¸»é¢˜æ¨¡å¼
theme: 
  switch: true 
  default: style-light # style-light style-dark

# Service Worker | æ¸è¿›å¼åº”ç”¨
sw: false

# Post wordcount | å­—æ•°ç»Ÿè®¡
# https://github.com/willin/hexo-wordcount
wordcount:
  enable: false
  count: true
  time: true

# That is it only render those page which has `katex: true` in Front-matter.
# math fomula
# https://katex.org/
katex:
  copy_tex: true
  global: false
  # Options are for katex rendering options: https://katex.org/docs/options.html
  # In page katex options are also possible and will be merged
  options: {}

# Blog search | æœç´¢
search:
  enable: false
  type: engine #local engine
  href: 'https://www.google.com/search?q=site:'
  # href: "https://www.baidu.com/s?wd=site:"
  # href: "https://www.bing.com/search?q=site:"
  domain: 

# Think of swup as being pjax on steroids. The concepts are similar to those used in barba.js or other transition libraries.
# https://swup.js.org/
# Whether swup is enabled | Swup æ’ä»¶
swup: true

# Datetime formatting | æ—¥æœŸæ ¼å¼åŒ–
datetime_foramt:
  post_card:
    type: date # date || updated
    date: YY/MM/DD
    time: HH:mm
    cover_date: DD
    cover_date2: YYYY/MM
  post_info:
    type: date
    date: YY/MM/DD
    time: HH:mm
  archive:
    type: date
    date: YY/MM/DD
    time: HH:mm

# Home page category card configuration | é¦–é¡µåˆ†ç±»å¡ç‰‡
categorie_card:
  enable: true
  len: 4
  list: ["ç¬”è®°", "æ•°ç ", "å‘“è¯­", "å¹´åº¦æ€»ç»“"]

# Lower right button | åŠŸèƒ½æŒ‰é’®å—
rightside:
  readmode: true
  aside: true

# Replace Broken Images | ç ´å›¾æ—¶é»˜è®¤å›¾ç‰‡
error_img:
  flink: /images/friend_404.gif
  post_page: /images/post_404.jpg

# Code highlighting configuration | ä»£ç é«˜äº®é…ç½®
highlight:
  theme: true # 
  title: default # mac | default
  copy: true # copy button
  lang: true # show the code language
  code_word_wrap: fasle #
  height_limit: 200 # unit: px

# Customize the template path | è‡ªå®šä¹‰æ¨¡å—
layout:
  path: layout
  # layout
  main:  _partial/main
  header: _partial/header
  banner: _partial/banner
  sidebar: _partial/sidebar/index
  footer: _partial/footer
  # post
  post_info: _partial/post/post-info
  post_content: _partial/post/post-content
  reward: _partial/post/reward
  post_copyright: _partial/post/post-copyright
  post_next_prev: _partial/post/post-next-prev
  post_card: _partial/post/post-card
  post_card_mini: _partial/post/post-card-mini
  # widget
  header_logo: _widget/header-logo
  header_menu: _widget/header-menu
  header_theme: _widget/header-theme
  header_search: _widget/header-search
  categorie: _widget/categorie
  paginator: _widget/paginator
  fixed_btn: _widget/fixed-btn
  post_toc: _widget/post-toc
  about_card: _widget/about-card
  search: _widget/search
  sidebar_user: _partial/sidebar/card/user
  sidebar_social: _partial/sidebar/card/social
  sidebar_info: _partial/sidebar/card/info
  sidebar_email: _partial/sidebar/card/email
  # third-party
  comment: _third-party/comment/index
  analytics: _third-party/web-analytics
  # animation
  page_loading: _partial/preloader/page-preloader
  mode_change:  _partial/preloader/change-mode-preloader
  # page
  page_about: _partial/page/about
  page_archive: _partial/page/archive
  page_category: _partial/page/category
  page_index: _partial/page/index
  page_links: _partial/page/links
  page_post: _partial/page/post
  page_tag: _partial/page/tag
  # other
  script: _partial/script
  head: _partial/head

# 404 config | 404 é…ç½®
not_found: 
  path: /
  name: not_found.name
  text: not_found.text