# Open Graph protocol
open_graph: true

# User info
user:
  name: æ— é—»æ²™æ´²
  first_name: æ²™æ´²
  last_name: æ— é—»
  email: shinotak@foxmail.com
  domain: https://wangzai-zzy.github.io
  avatar: /images/avatar.png
  describe: è®©æƒ…ç»ªè¢«çœ‹è§ï¼Œè®©ç—›è‹¦è¢«è¨€è¯´ã€‚

# Configure the icon information of the site
favicon:
  logo: /images/favicon.png
  dark_logo: /images/favicon_dark.png
  icon16: /images/favicon.png
  icon32: /images/favicon.png
  apple_touch_icon: /images/favicon.png
  visibilitychange: false
  hidden: /failure.ico # Displays an icon when not visible
  show_text: favicon.show_text
  hide_text: favicon.hide_text

# Theme resource files or plug-ins
assets:
  # The cdn configuration of the js inside the theme
  internal_provider: local
  # cdn configuration of third-party js
  third_party_provider: unpkg
  # The plug-in used by the theme
  plugin:
    hexo_theme_async:
      rowcss: css/plugins/bootstrap.row.css
      typing: js/plugins/typing.js
      search: js/plugins/local_search.js
			danmu: js/plugins/danmu.js
      main: js/main.js
  # Icon configuration
  icons: 
    type: font # font symbol
    css:  //at.alicdn.com/t/c/font_3549054_n096xdrq7me.css
    js:

# CDN User - defined plug-in
cdn:
  css: 
  js:
    head:
    base: 
    async: 
    defer: 

# The icon used by the theme
icons:
  # Theme switch icon
  sun: iconfont icon-sun
  moon: iconfont icon-moon
  # Home video play
  play: iconfont icon-play-circle
  # email icon
  email: iconfont icon-envelope
  # Category entry icon
  next: iconfont icon-arrow-alt-circle-rig
  # Date of article details
  calendar: iconfont icon-calendar-alt
  # Article details time
  clock: iconfont icon-clock
  # Author of article details
  user: iconfont icon-user1
  # Return to the top icon
  back_top: iconfont icon-arrow-alt-circle-up
  # close icon
  close: iconfont icon-times-circle
  # search icon
  search: iconfont icon-search
  # reward icon
  reward: iconfont icon-hand-holding-usd
  # User information and article directory switch
  user_tag: iconfont icon-user
  toc_tag: iconfont icon-th-list
  # Secure the button in the lower right corner
  read: iconfont icon-book-reader
  arrows: iconfont icon-arrows-alt-h
  # Code highlight fold icon
  double_arrows: iconfont icon-angle-double-down
  # Code copy icon
  copy: iconfont icon-copy

# Top navigation menu
top_bars:
  - title: ä¸»é¡µ
    url: /
  - title: å½’æ¡£
    url: /archives/
  - title: é“¾æ¥
    url: /links/
  - title: å…³äº
    url: /about/

# Banner settings
banner:
  use_cover: false
	danmu: 
		enable: false
		el: .trm-banner
  default:
    type: img
    bgurl: https://s2.loli.net/2024/07/29/bUwSQrg95tfeiHN.jpg
    position: top
    fit: cover
  index:
    type: img
    bgurl: https://s2.loli.net/2024/07/29/1G96t2w7XDENdf4.jpg
    bannerTitle: æˆ‘çŸ¥é“ï¼Œ<br>æ˜¯æµæ˜Ÿèµç¾äº†é»‘å¤œï¼Œ<br>é²¸é±¼å®‰æ…°äº†å¤§æµ·ã€‚
  archive:
    type: img
    bgurl: https://s2.loli.net/2024/07/29/4G2KZkqmz8QlHY9.jpg
    bannerTitle: æ¼«æ¸¸è€…å‘æ¸…æ™¨ç»¿è‰²çš„åœ°å¸¦é™è½ï¼Œ<br>ä¸‡ç‰©ç‡ƒçƒ§ã€‚
  links:
    type: img
    bgurl: https://s2.loli.net/2025/03/29/jzxQqV5XBPZ1Dkt.jpg
    bannerTitle: å¹¶éå› ä¸ºä¿¡ä»»æ‰å»äº†è§£ï¼Œ<br>è€Œæ˜¯å› ä¸ºæƒ³è¦ä¿¡ä»»ã€æƒ³è¦äº†è§£ã€‚
  about:
    type: img
    bgurl: https://s2.loli.net/2025/03/29/BmnrKGcloT3NSwa.jpg
    bannerTitle: FACE THE SIN, <br>SAVE THE E.G.O.

# Sidebar settings
sidebar:
  typed_text_prefix: 
  typed_text: [ 'ä¸–äº‹è¯¡è°²ï¼Œè°¨è‡´è‰¯çŸ¥', 'ä½†è¡Œå¥½äº‹ï¼Œè«é—®å‰ç¨‹' ]
  info: 
    - key: Residence
      val: Earth
  social:
    - name: BiliBili
      icon: iconfont icon-bilibili-fill
      url: https://space.bilibili.com/449552577
    - name: Weibo
      icon: iconfont icon-weibo-fill
      url: https://weibo.com/u/7348512128/
    - name: Steam
      icon: iconfont icon-steam1
      url: https://steamcommunity.com/profiles/76561198976175627/
    - name: Github
      icon: iconfont icon-github
      url: https://github.com/WangZai-ZZY

# About page settings
about:
	insert: none # before | after | none
  title: åœ¨è¿·èŒ«çš„æ—¶å€™ï¼Œäººåº”è¯¥é¡ºç€è‡ªå·±ä¸ç°å®çš„è”ç³»â€”â€”æ— è®ºé‚£æ˜¯ä¸€ç§ç”Ÿæ´»ï¼Œè¿˜æ˜¯ä¸€ç§ç†æƒ³â€”â€”å»å¯»æ‰¾æ–¹å‘ã€‚
  introduction: 
    å—¨ï¼è¿™é‡Œæ˜¯<strong>æ±ªå´½zzy</strong>ï¼Œæ¬¢è¿å…‰ä¸´æˆ‘çš„åšå®¢ğŸ‰ï¼
    <br><br>
    æˆ‘ä¸€ç›´è§‰å¾—ï¼Œæ ‡ç­¾åªèƒ½é™ä½äº¤å¾€çš„æˆæœ¬ï¼Œæ— æ³•çœŸæ­£è§¦åŠä¸€ä¸ªäººçš„å†…åœ¨ã€‚
    è€Œäººä¸äººä¹‹é—´çœŸæ­£çš„ç†è§£ä¸å…³æ€€ï¼Œæ˜¯ä»æ‰¿è®¤å¯¹æ–¹è¡Œä¸ºå…·æœ‰æ­£å½“æ€§ã€è§¦ç¢°å¹¶æ¥æ´½å¯¹æ–¹æƒ…æ„Ÿå¼€å§‹çš„ã€‚
    <br><br>
    æ‰€ä»¥ï¼Œæˆ‘é€‰æ‹©äº†åšå®¢è¿™ä¸€å½¢å¼ï¼Œå¸Œæœ›é€šè¿‡æ–‡å­—è¿™ä¸€è½½ä½“ï¼Œå¯„å®¿æˆ‘çš„æƒ…æ„Ÿï¼Œå‘å…‰ä¸´æ­¤åœ°çš„è®¿é—®è€…ä¼ è¾¾ã€‚
    æ— è®ºä½ æ˜¯å¦å¯¹æˆ‘è®²è¿°çš„æ•…äº‹äº§ç”Ÿäº†å…´è¶£ï¼Œæˆ‘éƒ½ååˆ†æ„Ÿè°¢ä½ çš„åˆ°è®¿â€”â€”<br>
    å› ä¸ºä½ çš„åˆ°æ¥ï¼Œæ‰è®©è¿™å¤„åƒ»é™ä¹‹åœ°æœ‰äº†ç”Ÿæœºã€‚
  blog: 
    <ul class="trm-list">
      <li>ä¸»é¡µé¡¶æ å›¾ï¼š<a href="http://www.uchor.com/U/1024975">ã€Œå››æ—¥ç«å…‰èŠ‚ã€-by. ç‹›çº³ä¸–ç•Œ</a></li>
      <li>å½’æ¡£é¡¶æ å›¾ï¼š<a href="https://hanyijie.lofter.com/post/d7b61_1cc897861">ã€Œè‰¾é›…æ³•æ‹‰ã€-by. éŸ©ä¸€æ°</a></li>
      <li>é“¾æ¥é¡¶æ å›¾ï¼š<a href="https://x.com/gggggoou/status/1815365337795445176">by. gow</a></li>
      <li>é“¾æ¥é¡¶æ å›¾ï¼š<a href="https://x.com/paofannu/status/1900508030904758372">ã€Œé˜¿ç±³å¨…ã€by. paofannu</a></li>
    </ul>

# Footer settings
footer:
  # Hexo link (Powered by Hexo).
  powered:
    enable: true
  # Beian icp information for Chinese users. In China, every legal website should have a beian icp in website footer.
  # https://beian.miit.gov.cn/
  beian:
    enable: false
    icp: 
  # Copyright date
  copyright_year: 2020
  # 
  live_time:
    enable: false
    prefix: footer.tips
    start_time: 04/10/2022 17:00:00
  #
  custom_text: Hosted by <a href="https://github.com" rel="noopener" target="_blank">&nbsp;Github Pages</a>

# Here is a collection of articles related to configuration.
#### Article configuration start ###
# Reward (Donate)
# If enable true, reward would be displayed in every posts and pages by default.
# You can show or hide reward in a specific page throuth `reward: true | false` in Front Matter.
reward:
  enable: false
  comment: reward.comment
  # url:
  methods:

# Article table of contents
toc:
  enable: true
  list_number: true
  post_title: true
  max_depth: 3
  min_depth: 1

# Archive page
archive:
  type: more # less more

# Creative Commons 4.0 International License.
# https://creativecommons.org/licenses/
# Available values of license: by | by-nc | by-nc-nd | by-nc-sa | by-nd | by-sa | zero
# You can set a language value if you prefer a translated version of CC license.
# CC licenses are available in 39 languages, where you can find the specific and correct abbreviation you need.
# Valid values of language: deed.zh, deed.en, deed.ja, etc.
creative_commons:
  license: by-nc-sa
  language: deed.zh
  post: false
  clipboard: false

# Customize the cover image
cover:
  default: /images/block_default.jpg
  type: date # img || date || random

# The previous and the next article
post_pagination: 
  enable: true 
  type: small # large || small

# img loading="lazy"
lazyload:
  enable: true

# Displays outdated notice for a post (æ–‡ç« è¿‡æœŸæé†’)
notice_outdate:
  enable: false
  style: flat # style: simple/flat
  limit_day: 365 # When will it be shown
  position: top # position: top/bottom
#### Article configuration end ###

# Page Visit Statistics
web_analytics:  
  enable: false 
  baidu:   # Baidu key
  google:  # Tracking ID for Google statistics
  tencent: # Tencent statistics
    sid:
    cid:

# comment
comment:
  bComments:
    enable: false
    env: # è…¾è®¯äº‘ç¯å¢ƒid
  twikoo:
    enable: false
    envId:   # è…¾è®¯äº‘ç¯å¢ƒid
  # region: # ç¯å¢ƒåœ°åŸŸï¼Œé»˜è®¤ä¸º ap-shanghaiï¼Œå¦‚æœæ‚¨çš„ç¯å¢ƒåœ°åŸŸä¸æ˜¯ä¸Šæµ·ï¼Œéœ€ä¼ æ­¤å‚æ•°
  # option: # ç”¨äºåŒºåˆ†ä¸åŒæ–‡ç« çš„è‡ªå®šä¹‰ js è·¯å¾„ï¼Œå¦‚æœæ‚¨çš„æ–‡ç« è·¯å¾„ä¸æ˜¯ location.pathnameï¼Œéœ€ä¼ æ­¤å‚æ•°
  giscus:
    enable: false
    repo:
    repo-id:
    category:
    category-id:
    mapping: pathname
    reactions-enabled: 1
    emit-metadata: 0
    lang: zh-CN
    theme: 
      light: light
      dark: transparent_dark

# Theme mode 
theme: 
  switch: true 
  default: style-light # style-light style-dark

# Service Worker
sw: false

# Post wordcount
# https://github.com/willin/hexo-wordcount
wordcount:
  enable: false
  count: true
  time: true

# That is it only render those page which has `katex: true` in Front-matter.
# math fomula
# https://katex.org/
katex:
  copy_tex: true
  global: false
  # Options are for katex rendering options: https://katex.org/docs/options.html
  # In page katex options are also possible and will be merged
  options: {}

# Blog search
search:
  enable: false
  type: engine #local engine
  href: 'https://www.google.com/search?q=site:'
  # href: "https://www.baidu.com/s?wd=site:"
  # href: "https://www.bing.com/search?q=site:"
  domain: 

# Think of swup as being pjax on steroids. The concepts are similar to those used in barba.js or other transition libraries.
# https://swup.js.org/
# Whether swup is enabled
swup: true

# Datetime formatting
datetime_foramt:
  post_card:
    type: date # date || updated
    date: YY/MM/DD
    time: HH:mm
    cover_date: DD
    cover_date2: YYYY/MM
  post_info:
    type: date
    date: YY/MM/DD
    time: HH:mm
  archive:
    type: date
    date: YY/MM/DD
    time: HH:mm

# Home page category card configuration
categorie_card:
  enable: true
  len: 4
  list: ["éšç¬”", "å‘“è¯­", "æ•°ç æŠ€æœ¯", "å¹´åº¦æ€»ç»“"]

# Lower right button
rightside:
  readmode: true
  aside: true

# Replace Broken Images 
error_img:
  flink: /images/friend_404.gif
  post_page: /images/post_404.jpg

# Code highlighting configuration
highlight:
  theme: true # 
  title: default # mac | default
  copy: true # copy button
  lang: true # show the code language
  code_word_wrap: fasle #
  height_limit: 200 # unit: px

# Customize the template path
layout:
  path: layout
  # layout
  main:  _partial/main
  header: _partial/header
  banner: _partial/banner
  sidebar: _partial/sidebar/index
  footer: _partial/footer
  # post
  post_info: _partial/post/post-info
  post_content: _partial/post/post-content
  reward: _partial/post/reward
  post_copyright: _partial/post/post-copyright
  post_next_prev: _partial/post/post-next-prev
  post_card: _partial/post/post-card
  post_card_mini: _partial/post/post-card-mini
  # widget
  header_logo: _widget/header-logo
  header_menu: _widget/header-menu
  header_theme: _widget/header-theme
  header_search: _widget/header-search
  categorie: _widget/categorie
  paginator: _widget/paginator
  fixed_btn: _widget/fixed-btn
  post_toc: _widget/post-toc
	about_card: _widget/about-card
	search: _widget/search
  sidebar_user: _partial/sidebar/card/user
  sidebar_social: _partial/sidebar/card/social
  sidebar_info: _partial/sidebar/card/info
  sidebar_email: _partial/sidebar/card/email
  # third-party
  comment: _third-party/comment/index
  analytics: _third-party/web-analytics
  # animation
  page_loading: _partial/preloader/page-preloader
  mode_change:  _partial/preloader/change-mode-preloader
  # page
  page_about: _partial/page/about
  page_archive: _partial/page/archive
  page_category: _partial/page/category
  page_index: _partial/page/index
  page_links: _partial/page/links
  page_post: _partial/page/post
  page_tag: _partial/page/tag
	# other
	script: _partial/script
	head: _partial/head

not_found: 
	path: /
	name: not_found.name
	text: not_found.text